### ISSUE TITLE
API retired?

### ISSUE THREAD

**Issue by rashidkpc** [PeaceCorps/Volunteer-Openings-API#1]
Looks like this API is gone. When accessed via `http` it 302s to `https`, which 301s to the the same URL with a trailing slash, which 404s 😢 .

```
$ curl -I -XGET https://www.peacecorps.gov/api/v1/openings/
HTTP/1.1 404 Not Found
Content-Type: text/html; charset=utf-8
Date: Sun, 06 Aug 2017 20:59:39 GMT
Server: nginx/1.10.3
```

**Comment by sshami** [comment]
@rashidkpc Yes, sorry, this API is not available since we switched to the new peacecorps.gov website. However, we have it in our queue to rebuild a volunteer openings API for the new website.
